name: WhaTap Tech Blog
description: 와탭 기술 블로그
meta_description: "WhaTap Tech Blog입니다."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://tech.whatap.io'
google_analytics: 'UA-58355070-4'
permalink: pretty
